### ISSUE TITLE
SSL Validation warning is being applied to instances that are not SSL

### ISSUE THREAD

**Issue by miketheman** [DataDog/dd-agent#1195]
A config:

``` yaml
instances:
  - name: Datadog.com
    url: http://www.datadog.com
    timeout: 1
    collect_response_time: true
    skip_event: true
    headers:
      User-Agent: DatadogAgent 5.x

  - name: Datadoghq.com
    url: https://www.datadoghq.com/
    timeout: 1
    collect_response_time: true
    skip_event: true
    headers:
      User-Agent: DatadogAgent 5.x
```

Note that only one of these has SSL in the URL.

`info` command will show warnings, and change which Instance they apply to randomly.

``` console
    http_check
    ----------
      - instance #0 [OK]
      - instance #1 [WARNING]
          Warning: Skipping SSL certificate validation for http://www.datadog.com based on configuration
```
