### ISSUE TITLE
[windows] Raw performance counters cannot be easily used

### ISSUE THREAD

**Issue by miketheman** [DataDog/dd-agent#1244]
The Win32_PerfFormattedData_PerfDisk_PhysicalDisk class will round certain metrics up to seconds.
For example:

> AvgDiskSecPerTransfer
Data type: uint32
Access type: Read-only
Qualifiers: CookingType ("PERF_AVERAGE_TIMER") , Counter ("AvgDiskSecPerTransfer") , PerfTimeStamp ("Timestamp_PerfTime") , PerfTimeFreq ("Frequency_PerfTime") , Base ("AvgDiskSecPerTransfer_Base")
Time, in seconds, of the average disk transfer.

From http://msdn.microsoft.com/en-us/library/aa394262%28VS.85%29.aspx

This means that when using the WMI Query interface, we are unable to detect anything sub-second.

```powershell
> $query1 = "Select AvgDisksecPerRead, AvgDisksecPerWrite, AvgDisksecPerTransfer from Win32_PerfFormattedData_PerfDisk_PhysicalDisk Where Name = '_Total'"
> DO { Get-WmiObject -Query $query1 | Select-Object Avg* | Format-List} WHILE ($true)

AvgDisksecPerRead     : 0
AvgDisksecPerTransfer : 0
AvgDisksecPerWrite    : 0

AvgDisksecPerRead     : 0
AvgDisksecPerTransfer : 0
AvgDisksecPerWrite    : 0
...
```

However, these gauge values are "cooked" - they are reported in seconds, with the [PERF_AVERAGE_TIMER type](http://msdn.microsoft.com/en-us/library/ms804010.aspx). 

Therefore, it is recommended to collect data from the raw metrics class, however there we need to calculate ourselves the interval between samples, then calculate the difference to get an "average over time period".

```powershell
> $query2 = "Select AvgDisksecPerRead, AvgDisksecPerWrite, AvgDisksecPerTransfer from Win32_PerfRawData_PerfDisk_PhysicalDisk Where Name = '_Total'"
> DO { Get-WmiObject -Query $query2 | Select-Object Avg* | Format-List} WHILE ($true)

AvgDisksecPerRead     : 179311811
AvgDisksecPerTransfer : 784781729
AvgDisksecPerWrite    : 605469917

AvgDisksecPerRead     : 179509423
AvgDisksecPerTransfer : 784980860
AvgDisksecPerWrite    : 605471437
```

As can be seen, the values increate over time, so I think we have something builtin that can handle the calculation, but I wasn't able to figure it out.

Here's some yaml I tried in wmi_check.yaml:
```yaml
    - class: Win32_PerfRawData_PerfDisk_PhysicalDisk
      metrics:
        - [AvgDiskSecPerTransfer, Latency_Total.AVG.Time, $METRIC_TYPE]
        - [AvgDiskSecPerRead, Latency_Read.AVG.Time, $METRIC_TYPE]
        - [AvgDiskSecPerWrite, Latency_Write.AVG.Time, $METRIC_TYPE]
      tag_by: Name
```

Where I tried replacing $METRIC_TYPE with `gauge` (definitely wrong), `count`, `monotonic_count`, `histogram` - and was unable to accurately represent a millisecond value for this metric collector.

Maybe there's some post-processing that needs to be done, or another type I'm missing?

PS: There may be another way to retrieve these metrics via `Get-Counter`, but this would make the interface a little more complex, and I was unable to filter it correctly to get `_Total` vs `C:` drive, nor format it correctly that an Agent Check would accept.
