### ISSUE TITLE
Changing days_warning doesn't reset in the web interface until you change the instance name.

### ISSUE THREAD

**Issue by darron** [DataDog/dd-agent#1387]
Testing http_check today and set an artificially long time (400 days) to force a warning.

When I forced the warning and then changed it back to 30 the warning never went away.

I had to change the instance name in order for the warning to go away and reset back to OK.

```
init_config:

instances:
  - name: octohost-new
    url: https://www.octohost.io
    timeout: 1
    collect_response_time: true
    disable_ssl_validation: false
    check_certificate_expiration: true
    days_warning: 30
    skip_event: true
```

Is that a known issue?
