### ISSUE TITLE
postgres check should collect connection state - active vs idle

### ISSUE THREAD

**Issue by miketheman** [DataDog/dd-agent#1828]
This would help with diagnoses on when things get busy.

Also, adding a custom field like [`application_name`](http://www.postgresql.org/docs/current/static/runtime-config-logging.html#GUC-APPLICATION-NAME) - maybe as a tag? - might be a nice-to-have.

**Comment by miketheman** [comment]
Came back to this, over a year, and find myself still wanting this functionality.

**Comment by miketheman** [comment]
I found one way to achieve this, with the under-documented `custom_metrics` functionality.

```yaml
custom_metrics:
  - # Postgres Connection state
    descriptors:
      - [datname, database]
      - [application_name, application_name]
      - [state, state]
    metrics:
      COUNT(state): [postgresql.connection_state, GAUGE]
    query: >
      SELECT datname, application_name, state, %s FROM pg_stat_activity
      GROUP BY datname, application_name, state HAVING COUNT(state) > 0;
    relation: false
```

This doesn't account for `application_name` being empty, to the resulting tag can show `application_name:` with no value, so it would be nice to have some method for expressing "apply tag only if is a non-null value"

It would also be ideal if these metrics made their way into the core, and possibly be part of the `postgres.connections` metric, but that one is retrieved from a different `pg_stat_*` table.
