### ISSUE TITLE
conf.d checks combined and in many different files

### ISSUE THREAD

**Issue by smaant** [DataDog/dd-agent#2090]
Hello.

As I understand, if I want to add custom http checks, I have to put all of them into a `http_check.yaml` file in `conf.d` folder. I cant find a good deployment solution for this in case then I have multiple services running on one server. In particular I have many docker containers with different services and one container with dd-agent. Now I have to somehow aggregate all http_checks from all services and combine them into single `http_check.yaml` and then put it into dd-agent container.
It would be nice to be able to separate http (and any other) checks in many files and also to be able to combine different types of checks in one file, for instance it may looks like:
```yaml
# backend_checks.yaml
init_config:

instances:
  - type: http_check
    name: backend check
    url: http://localhost:3000

  - type: ntp
    offset_threshold: 60
```

```yaml
# service_checks.yaml
init_config:

instances:
  - type: http_check
    name: service check
    url: http://localhost:3001

  - type: rabbitmq
    rabbitmq_api_url: http://localhost:15672/api/
```
