### ISSUE TITLE
Restart problem with datadog-agent if configured mongo not running

### ISSUE THREAD

**Issue by spiritmonger** [DataDog/dd-agent#2330]
datadog-agent: 5.7.0
os: amazon linux 2015.09

configured mongo (/etc/dd-agent/conf.d/mongo.yaml):

```
instances:
  - server: mongodb://localhost/db1:27017
    tags:
    - db1
  - server: mongodb://localhost/admin:27017
    tags:
    - admin

init_config:
# No init_config details needed
```

PROBLEM
if mongo not running, datadog can't stop correctly. If i tried restart, i saw:

```
$ service datadog-agent restart
Stopping Datadog Agent (using killproc on supervisord):    [  OK  ]
Starting Datadog Agent (using supervisord):Unlinking stale socket /opt/datadog-agent/run/datadog-supervisor.sock

datadog-agent:collector          FATAL     Exited too quickly (process log may have details)
datadog-agent:dogstatsd          RUNNING   pid 14792, uptime 0:00:10
datadog-agent:forwarder          RUNNING   pid 14794, uptime 0:00:10
datadog-agent:go-metro           EXITED    Mar 08 02:27 PM
datadog-agent:jmxfetch           EXITED    Mar 08 02:27 PM
Datadog Agent (supervisor) is NOT running all child process[FAILED]
Stopping Datadog Agent (using killproc on supervisord):    [  OK  ]
```

...and i saw in process list is "/opt/datadog-agent/embedded/bin/python /opt/datadog-agent/agent/agent.py foreground --use-local-forwarder"

Can't restarting datadog-agent immediately, with stopped mongo. 

---

if agent.py process had finished/died, then is possible start datadog-agent!
if mongo is running, then can restart datadog-agent.
if i use datadog-agent package version 5.6.3, then restart working correctly.
