### ISSUE TITLE
MySQL integration throws error with RDS Aurora Reader

### ISSUE THREAD

**Issue by hybby** [DataDog/dd-agent#2579]
I've configured the MySQL Integration against two instances of an AWS RDS Aurora database, which is MySQL compatible.  The first is a writer (master) and is reporting fine.  The second is a reader (read-replica) is returning a Python stack trace when invoking `dd-agent info`:

```
# dd-agent info -v
===================
Collector (v 5.8.0)
===================

  Status date: 2016-06-08 04:45:20 (8s ago)
  Pid: 34816
  Platform: Linux-3.2.0-88-virtual-x86_64-with-debian-wheezy-sid
  Python Version: 2.7.11, 64bit
  Logs: <stderr>, /var/log/datadog/collector.log, syslog:/dev/log
...snip...
      - instance #11 [OK]
      - instance #12 [ERROR]: "'NoneType' object has no attribute '__getitem__'"
        Traceback (most recent call last):
          File "/opt/datadog-agent/agent/checks/__init__.py", line 750, in run
            self.check(copy.deepcopy(instance))
          File "/opt/datadog-agent/agent/checks.d/mysql.py", line 314, in check
            raise e
        TypeError: 'NoneType' object has no attribute '__getitem__'
...snip...
```

In this case, `instance #11` is the writer (master) and `instance #12` is the reader (read-replica).  I have other RDS instances configured up with this integration on this host, which is why the numbers are larger than you'd expect.

Configuration file `/etc/dd-agent/conf.d/mysql.yaml` looks like so, with site-specific items removed:

```
  - server: <omitted>.rds.amazonaws.com
    user: <omitted>
    pass: <omitted>
    tags:
      - "mysql_host:<omitted>.rds.amazonaws.com"
      - "purpose:<omitted>"
      - "project:<omitted>"
      - "environment:<omitted>"
    options: # Optional
      replication: true
      galera_cluster: 0
  - server: <omitted>.rds.amazonaws.com
    user: <omitted>
    pass: <omitted>
    tags:
      - "mysql_host:<omitted>.rds.amazonaws.com"
      - "purpose:<omitted>"
      - "project:<omitted>"
      - "environment:<omitted>"
    options: # Optional
      replication: true
      galera_cluster: 0
```

How can I troubleshoot this issue further?  

As noted, the writer (master) instance seems to operate fine.  It's just the second reader (read-replica) that's throwing this traceback.

Curious as to whether I should just configure this up pointing at the cluster endpoint rather than a configuration stanza for each node of the cluster.
