### ISSUE TITLE
mysql.replication.slave_running returns Critical state on master node

### ISSUE THREAD

**Issue by DanielMuller** [DataDog/dd-agent#2596]
In a MySQL RDS master-slave setup, setting _replication:true_ on both master and slave config result in an unwanted _critical_ check state. Setting it on slave, returns the correct OK check status.
Setting _replication:true_ on master allows to populate _mysql.replication.slaves_connected_

I am expecting an OK status from master when master has a running slave. Or at least no check at all.

Example mysql.yaml:
```yaml
instances:
  - server: my_master.rds.amazonaws.com
    port: 3306
    user: datadog
    pass: XXXXXX
    tags:
      - dbinstanceidentifier:my_master
    options:
      replication: true
  - server: my_slave.rds.amazonaws.com
    port: 3306
    user: datadog
    pass: XXXXXX
    tags:
      - dbinstanceidentifier:my_slave
    options:
      replication: true
```
