### ISSUE TITLE
supervisord #0 [ERROR]: 'unsupported XML-RPC protocol'

### ISSUE THREAD

**Issue by czerasz** [DataDog/dd-agent#2682]
I get this issue while running the agent inside a Docker container:

```
docker run -d --name dd-agent \
           -h `hostname` \
           -v /var/run/docker.sock:/var/run/docker.sock \
           -v /proc/:/host/proc/:ro \
           -v /sys/fs/cgroup/:/host/sys/fs/cgroup:ro \
           -v $PWD/dd-agent/conf.d:/conf.d:ro \
           -v /var/run/supervisor.sock:/var/run/supervisor.sock \
           -e API_KEY=... \
           -e TAGS='staging' \
           datadog/docker-dd-agent:latest
```

Here is my `supervisord.yaml` configuration file:

```

init_config:

instances:
  - name: test01-server
    host: test01-server
    user: user       # Optional. Required only if a username is configured.
    pass: pass123       # Optional. Required only if a password is configured.
    socket: unix:///var/run/supervisor.sock
    tags:
      - staging
```

Here is the info status:

```
$ docker exec dd-agent service datadog-agent info
===================
Collector (v 5.8.4)
===================

  Status date: 2016-07-13 14:53:28 (13s ago)
  Pid: 43
  Platform: Linux-3.13.0-83-generic-x86_64-with-debian-8.5
  Python Version: 2.7.11, 64bit
  Logs: <stderr>, /var/log/datadog/collector.log

  Clocks
  ======
  
    NTP offset: 0.0021 s
    System UTC time: 2016-07-13 14:53:42.532826
  
  Paths
  =====
  
    conf.d: /etc/dd-agent/conf.d
    checks.d: /opt/datadog-agent/agent/checks.d
  
  Hostnames
  =========
  
    socket-hostname: test01-server
    hostname: test01-server
    socket-fqdn: test01-server
  
  Checks
  ======
  
    supervisord
    -----------
      - instance #0 [ERROR]: 'unsupported XML-RPC protocol'
      - Collected 0 metrics, 0 events & 1 service check
  
    ntp
    ---
      - Collected 0 metrics, 0 events & 1 service check
  
    disk
    ----
      - instance #0 [OK]
      - Collected 32 metrics, 0 events & 1 service check
  
    ...
  
  
  Emitters
  ========
  
    - http_emitter [OK]

===================
Dogstatsd (v 5.8.4)
===================

  Status date: 2016-07-13 14:53:33 (9s ago)
  Pid: 38
  Platform: Linux-3.13.0-83-generic-x86_64-with-debian-8.5
  Python Version: 2.7.11, 64bit
  Logs: <stderr>, /var/log/datadog/dogstatsd.log

  Flush count: 17
  Packet Count: 0
  Packets per second: 0.0
  Metric count: 1
  Event count: 0
  Service check count: 0

===================
Forwarder (v 5.8.4)
===================

  Status date: 2016-07-13 14:53:43 (0s ago)
  Pid: 40
  Platform: Linux-3.13.0-83-generic-x86_64-with-debian-8.5
  Python Version: 2.7.11, 64bit
  Logs: <stderr>, /var/log/datadog/forwarder.log

  Queue Size: 469 bytes
  Queue Length: 1
  Flush Count: 59
  Transactions received: 24
  Transactions flushed: 23
  Transactions rejected: 0
```

I'm running Supervisor in version `3.2.0`:

```
$ supervisord -v
3.2.0
```
