### ISSUE TITLE
MongoDB Replica Set Unable to Authenticate

### ISSUE THREAD

**Issue by Crispy1975** [DataDog/dd-agent#2703]
We are trying to get the DataDog agent to authenticate to a MongoDB replica set, the below is what we see in the collector logs over and over. The RS itself is 3 node and uses `ssl`. We have a `DataDog` user configured with the correct roles and have confirmed we can connect and see the `admin` database on the MongoDB cluster.

### Error Output
```shell
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/__init__.py", line 750, in run
    self.check(copy.deepcopy(instance))
  File "/opt/datadog-agent/agent/checks.d/mongo.py", line 634, in check
    if do_auth and not db.authenticate(username, password):
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/pymongo/database.py", line 1023, in authenticate
    connect=True)
  File "/opt/datadog-agent/embedded/lib/python2.7/site-packages/pymongo/mongo_client.py", line 413, in _cache_credentials
    raise OperationFailure('Another user is already authenticated '
OperationFailure: Another user is already authenticated to this database. You must logout first.
```

### DataDog User
```json
[
        {
                "_id" : "admin.admin",
                "user" : "admin",
                "db" : "admin",
                "roles" : [
                        {
                                "role" : "root",
                                "db" : "admin"
                        }
                ]
        },
        {
                "_id" : "admin.AppUser",
                "user" : "AppUser",
                "db" : "admin",
                "roles" : [
                        {
                                "role" : "readWriteAnyDatabase",
                                "db" : "admin"
                        }
                ]
        },
        {
                "_id" : "admin.DataDog",
                "user" : "DataDog",
                "db" : "admin",
                "roles" : [
                        {
                                "role" : "readAnyDatabase",
                                "db" : "admin"
                        },
                        {
                                "role" : "clusterMonitor",
                                "db" : "admin"
                        }
                ]
        }
]
```

### MongoDB DataDog YAML
```yaml
init_config:

instances:
  - server: mongodb://DataDog:*******@10.128.0.7:27017,10.128.0.8:27017,10.128.0.9:27017/admin?authMechanism=SCRAM-SHA-1&authSource=admin&replicaSet=RS-Testing-0&ssl=true
    timeout: 30
    tags:
      - key:value
    additional_metrics:
      - durability
      - locks
      - top
    ssl: True
    ssl_keyfile: /etc/ssl/mongodb.pem
    ssl_certfile: /etc/ssl/mongodb.pem
    ssl_cert_reqs: 0
    ssl_ca_certs: /etc/ssl/mongodb.pem
```

When testing we made sure that nobody was logged in using the `DataDog` credentials, but we still see the `OperationFailure: Another user is already authenticated to this database. You must logout first.` error in the logs.

Any ideas would be greatly appreciated.
