### ISSUE TITLE
[mysql] float division by zero

### ISSUE THREAD

**Issue by TrurlMcByte** [DataDog/dd-agent#2777]
mysql monitoring problem in case of `performance_schema=off` in `[mysqld]` settings
```
    mysql
    -----
      - instance #0 [ERROR]: 'float division by zero'
      - Collected 0 metrics, 0 events & 3 service checks
```
instance options is
```
    options:
        replication: false
        galera_cluster: false
        extra_performance_metrics: false
```
Both agent and mysqld running on same `CoreOS` server (official `mysql:5.7` used)
(on neighbor server same set, but without `performance_schema=off` working fine)
