### ISSUE TITLE
[HTTP/TCP Check] Add support for multiple DSNs

### ISSUE THREAD

**Issue by gonzaloserrano** [DataDog/dd-agent#2818]
Scenario: i have 20 apps in the same server that i want to TCP check. This is usually an integration server for testing purposes.

Instead of doing:
```
      instances:
        - name: App env 0
          host: localhost
          port: 8000
          timeout: 1
          threshold: 3
          skip_event: true

        - name: App env 1
          host: localhost
          port: 8001
          timeout: 1
          threshold: 3
          skip_event: true

        ⋮

        - name: App env 20
          host: localhost
          port: 8020
          timeout: 1
          threshold: 3
          skip_event: true
```

I'd like something like:

```
        - name: App env 20
          dsns: 
              - localhost:8000
              - localhost:8001

              ⋮

              - localhost:8020
          timeout: 1
          threshold: 3
          skip_event: true
```

What do you think?
