### ISSUE TITLE
If kafka_consumer.py can accept multiple ZK/Kafka servers, document it

### ISSUE THREAD

**Issue by jeffwidman** [DataDog/dd-agent#2943]
It's not clear from https://github.com/DataDog/dd-agent/blob/master/conf.d/kafka_consumer.yaml.example whether the Kafka and Zookeeper hosts can be a list or only a single host. In a production environment, a list is preferable for redundancy.

If this is possible, it should be documented.

**Comment by yannmh** [comment]
@jeffwidman,

The Kafka and Zookeper hosts parameters are singleton (or they would be prefixed with `-` to follow the YAML syntax rules). 

However, all checks YAML configuration files support multiple instances, which I believe, is what you are looking for. For example:

```yaml
init_config:

instances:
  - kafka_connect_str: [...]
    zk_connect_str: [...]
  - kafka_connect_str: [...]  # a second instance
    zk_connect_str: [...]
```

Please let me know if that helps.

**Comment by jeffwidman** [comment]
No, in this case the connect strings are passed straight to the underlying libraries. So they can be a YAML singleton, even though they are actually a concatenated list of multiple ZK/Kafka hosts. 

And you don't want it to be multiple instances, because then you're running the datadog check against each instance.

Instead, you want the it to be a single instance generating a single check process, with a list of multiple hosts passed through to `KazooClient` and `KafkaClient` so that if one host is down the library can try contacting the next host in the string. 

This could technically be done as a YAML sub-list that's passed to a single instance, but then you have to manually concatenate within the check. In this case, I think simplest/most straightforward to manually do the concatenated list for `kafka_connect_str` and `zk_connect_str`. 

The question I had is ultimately whether `KazooClient` and `KafkaClient` support strings of multiple hosts. This is the way the Java consumers/producers for Kafka work, I just wasn't sure it was how `kafka-python` worked or not.

**Comment by yannmh** [comment]
Thanks for the clarification @jeffwidman,

So i had a look and figured out this was possible with a single instance: 
* `KazooClient` expects a comma-separated list of hosts
* `KafkaClient`, a string or list of 'host[:port]' strings

In practice, it means the `kafka_consumer.yaml` file can be defined as follow:

```yaml
init_config:

instances:
  - kafka_connect_str: 
    - <kafka_host1:port>
    - <kafka_host2:port>
    zk_connect_str: <zk_host1:port>,<zk_host2:port>
```
