### ISSUE TITLE
to monitor multiple postgres instances

### ISSUE THREAD

**Issue by megadawn** [DataDog/dd-agent#3065]
Hi,
How can i add a second postgres DB to the datadog? something like:
instances:
  - name: PG1
    host: server1
    port: 1521
    username: datadog
    password: 12345
    dbname: db1
    tags:
      - postgres1

  - name: PG2
    host: server1
    port: 5432
    username: datadog
    password: 54321
    dbname: db2
    tags:
      - postgres2
?

**Comment by jimmystewpot** [comment]
```
instances:
  - host: PG1
    port: 5432
#    username: my_username
#    password: my_password
#    dbname: db_name
#    ssl: False
#    use_psycopg2: False # Force using psycogp2 instead of pg8000 to connect. WARNING: psycopg2 doesn't support ssl mode.
#    tags:
#      - optional_tag1
#      - optional_tag2
  - host: PG2
    port: 5432
#    username: my_username
#    password: my_password
#    dbname: db_name
#    ssl: False
#    use_psycopg2: False # Force using psycogp2 instead of pg8000 to connect. WARNING: psycopg2 doesn't support ssl mode.
#    tags:
#      - optional_tag1
#      - optional_tag2
```
