### ISSUE TITLE
[ntp] always used first instance's `host`  even if second and subsequent instances

### ISSUE THREAD

**Issue by hirose31** [DataDog/dd-agent#3090]
I wrote conf.d/ntp.yaml contains two instances:

```
init_config:

instances:
  - offset_threshold: 2
    host: 127.0.0.1
  - offset_threshold: 2
    host: time1.google.com
```

But always used first instance's `host` (=`127.0.0.1`) even if second instance.

The reason seems:

- ntp.py calls NTPUtil() without arguments https://github.com/DataDog/dd-agent/blob/master/checks.d/ntp.py#L27
- NTPUtil() always use setting of first instance https://github.com/DataDog/dd-agent/blob/master/utils/ntp.py#L28
