### ISSUE TITLE
Elasticsearch auto_conf service discovery fails with cluster port exposed

### ISSUE THREAD

**Issue by ferdy-lw** [DataDog/dd-agent#3128]
I have an image that exposes two ports, 9200 and 9300. If I run this image in Kubernetes with the dd_agent daemonset it auto discovers the elasticsearch container but attempts to get statistics from port 9300 rather than 9200.

This is because the `auto_conf/elastic.yaml` uses instances `url: "http://%%host%%:%%port%%"` The `%%port%%` picks the _last_ port number in the list, which is the wrong one. It should probably not use the port template but default to 9200.

I can't seem to find a way to override that file check either, it _always_ discovers that container and attempts to get checks from it.

Annotations don't appear to work (also the annotation [documentation](http://docs.datadoghq.com/guides/servicediscovery/#configuration-templates-with-kubernetes-annotations) doesn't match the [code](https://github.com/DataDog/dd-agent/blob/13d63df18715215d5e47b9adcfd1149a143d8181/utils/service_discovery/abstract_config_store.py#L104) - the annotation should be `/` separated from the prefix) :

```
  template:
    metadata:
      name: es
      labels:
        app: es
      annotations:
        service-discovery.datadoghq.com/es.check_names: '["elastic"]'
        service-discovery.datadoghq.com/es.init_configs: '[{}]'
        service-discovery.datadoghq.com/es.instances: '[{"url": "http://%%host%%:9200"}]'
    spec:
      containers:
        - name: es
```

It never picks up this annotation (which comes from a pod created via a deployment/replicaset). Looking at the code the annotation should override the auto_check file in the directory but I'm always getting pinged on the cluster port which ends up failing.

How can I *stop* it from trying collect metrics for this one service (elastic) without disabling all the other ones?

Collector (v 5.10.1)

**Comment by hkaj** [comment]
Hi @ferdy-lw 

Thanks for the detailed report.

It seems the documentation update was released too soon, and has a mistake as you pointed out. However the code you link to is on master but not released yet: the prefix your 5.10.1 agent is looking for is here: https://github.com/DataDog/dd-agent/blob/5.10.1/utils/service_discovery/abstract_config_store.py#L29 and the container name is also not needed (which is actually an issue that the new format fixes as the check may try and apply to all containers in the pod).

Thanks also for pointing out the port selection issue, we'll fix that. You can apply this change on your side in the meantime by replacing `%%port%%` with `%%port_0%%` in the auto_conf file (or override the auto_config with annotations in the current supported format instead).
To override the default config file you can use [the mounted conf.d feature](https://github.com/DataDog/docker-dd-agent/#configuration-files), just make sure to write the updated version under an `auto_conf` subdir in the folder you will mount.

**Comment by hkaj** [comment]
Ah that was auto-closed by merging the PRs. Feel free to re-open if you feel my answer and the PRs didn't solve your issue.

**Comment by ferdy-lw** [comment]
Thanks for the updates. I updated the annotations as per the older format and this works fine with 5.10.1: 

```
  template:
    metadata:
      name: es
      labels:
        app: es
      annotations:
        com.datadoghq.sd/check_names: '["elastic"]'
        com.datadoghq.sd/init_configs: '[{}]'
        com.datadoghq.sd/instances: '[{"url": "http://%%host%%:9200"}]'
```

I run 3 elasticsearch instances over different namespaces (one set clustered, one not) and the auto discovery picked them all up and reports them. I picked port 9200 rather than the port template as that is the port that I know to  have exposed.

I did not try the mount (with the auto_conf subdir), that would work I think, but it may have the caveat that that entire directory is replaced with the mount, you can't just do single files so one would have to make sure the mounted dir had all the auto_conf files wanted.
