### ISSUE TITLE
Incorrect tags are sent in Elasticsearch integration

### ISSUE THREAD

**Issue by ganta** [DataDog/dd-agent#3135]
**Output of the [info page](https://help.datadoghq.com/hc/en-us/articles/203764635-Agent-Status-and-Information)**

```
$ sudo /etc/init.d/datadog-agent status
Datadog Agent (supervisor) is running all child processes  [  OK  ]

$ sudo /etc/init.d/datadog-agent info
===================
Collector (v 5.7.4)
===================

  Status date: 2017-01-19 15:35:50 (4s ago)
  Pid: 2867
  Platform: Linux-3.14.44-32.39.amzn1.x86_64-x86_64-with-glibc2.3
  Python Version: 2.7.11, 64bit
  Logs: <stderr>, /var/log/datadog/collector.log, syslog:/dev/log

  Clocks
  ======

    NTP offset: -0.0002 s
    System UTC time: 2017-01-19 06:35:55.416220

  Paths
  =====

    conf.d: /etc/dd-agent/conf.d
    checks.d: /opt/datadog-agent/agent/checks.d

  Hostnames
  =========

    ec2-hostname: ip-10-0-0-203.ap-northeast-1.compute.internal
    local-ipv4: 10.0.0.203
    local-hostname: ip-10-0-0-203.ap-northeast-1.compute.internal
    public-hostname: ec2-*****.ap-northeast-1.compute.amazonaws.com
    hostname: *****
    instance-id: i-********
    public-ipv4: *****
    agent-hostname: *****
    socket-fqdn: localhost.localdomain

  Checks
  ======

    ntp
    ---
      - Collected 0 metrics, 0 events & 1 service check

    disk
    ----
      - instance #0 [OK]
      - Collected 40 metrics, 0 events & 1 service check

    network
    -------
      - instance #0 [OK]
      - Collected 27 metrics, 0 events & 1 service check

    elastic
    -------
      - instance #0 [OK]
      - instance #1 [OK]
      - instance #2 [OK]
      - Collected 518 metrics, 0 events & 7 service checks


  Emitters
  ========

    - http_emitter [OK]

===================
Dogstatsd (v 5.7.4)
===================

  Status date: 2017-01-19 15:35:55 (1s ago)
  Pid: 2860
  Platform: Linux-3.14.44-32.39.amzn1.x86_64-x86_64-with-glibc2.3
  Python Version: 2.7.11, 64bit
  Logs: <stderr>, /var/log/datadog/dogstatsd.log, syslog:/dev/log

  Flush count: 1639045
  Packet Count: 283423605
  Packets per second: 0.0
  Metric count: 1
  Event count: 0
  Service check count: 0

===================
Forwarder (v 5.7.4)
===================

  Status date: 2017-01-19 15:35:55 (3s ago)
  Pid: 2863
  Platform: Linux-3.14.44-32.39.amzn1.x86_64-x86_64-with-glibc2.3
  Python Version: 2.7.11, 64bit
  Logs: <stderr>, /var/log/datadog/forwarder.log, syslog:/dev/log

  Queue Size: 465 bytes
  Queue Length: 1
  Flush Count: 5333875
  Transactions received: 2473997
  Transactions flushed: 2473996
```

**Additional environment details (Operating System, Cloud provider, etc):**

OS: Amazon Linux
Datadog Agent: v5.7.4 (from https://yum.datadoghq.com/rpm/x86_64/ )
Elasticsearch: v2.4.2 (on Elastic Cloud)

**Steps to reproduce the issue:**

1. `/etc/dd-agent/conf.d/elastic.yaml` was configured as follows:

```yml
init_config:

instances:
  # production
  - url: <production environment url>
    username: *****
    password: *****
    cluster_stats: true
    # pshard_stats: false
    # pending_task_stats: true
    tags:
      - 'elasticsearch'
      - 'env:production'
  # preview
  - url: <preview environment url>
    username: *****
    password: *****
    cluster_stats: true
    # pshard_stats: false
    # pending_task_stats: true
    tags:
      - 'elasticsearch'
      - 'env:preview'
  # staging
  - url: <staging environment url>
    username: *****
    password: *****
    # pshard_stats: false
    # pending_task_stats: true
    tags:
      - 'elasticsearch'
      - 'env:staging'
```

2. Reload settings

```
$ sudo service datadog-agent reload
```

**Describe the results you received:**

`env:production` tag is sent to Datadog from the staging environment.

![datadog_elasticsearch_metrics](https://cloud.githubusercontent.com/assets/471182/22096912/9779ea86-de61-11e6-967a-1c2553de747b.png)

**Describe the results you expected:**

Tags are sent as configured.

**Additional information you deem important (e.g. issue happens only occasionally):**

I tried to stop sending data from this Datadog Agent and confirmed that no data was sent from another agent.
