### ISSUE TITLE
Any reason why Service Discovery is not supported for JMX checks?

### ISSUE THREAD

**Issue by Lawouach** [DataDog/dd-agent#3336]
Hi all,

I spent a good chunk of my morning trying to figure out why my JMX check wasn't picked up by the agentd and then I saw this:

https://github.com/DataDog/dd-agent/blob/master/jmxfetch.py#L202

Is there a reason why SD isn't supported for JMX checks? This is not intuitive why.

This was already hinted in #2862 but without any feedback since then.

Note, my JMX conf works well when I set it in `conf.d`. However, I'm running containers so this is not an option. As I'm using Kubernetes, I guess I can try annotations but I would have liked to keep my configurations in the agent itself.

Thanks.

**Comment by hkaj** [comment]
Hi @Lawouach 
SD should work for JMX checks. May I ask how you configure it? If you drop template files in the `auto_conf` folder they should be picked up. Also, did you enable this option in datadog.conf https://github.com/DataDog/dd-agent/blob/5.13.2/datadog.conf.example#L133-L134 ?

**Comment by Lawouach** [comment]
Hi @hkaj, thanks for the feeback.

Indeed, that is enabled. But, I wonder how they are meant to be picked up considering the line I linked to above?

Is there a log I could look up saying "okay I read that config but nothing I can do with it"?

**Comment by Lawouach** [comment]
By the way this is my condig:

```
docker_images:
  - myproj

init_config:

instances:
  - host: "%%host%%"
    port: 6001

    conf:
      - include:
          domain: myapp
          bean:
            - mbeanServer
```

When I put this under `conf.d/auto_conf`, nothing seems to happen. When I put it under `conf.d` with the IP of the container, it works fine.
