### ISSUE TITLE
[SQL Server] Defining instance in sqlserver.yaml is not picked up in initialization checks 

### ISSUE THREAD

**Issue by vin-yu** [DataDog/dd-agent#3343]
I constantly get the following error when i run /etc/init.d/datadog-agent info -v:

    sqlserver (unknown)
    -------------------
      - initialize check class [ERROR]: 'You need to have at least one instance defined in the YAML file for this check'
        Traceback (most recent call last):
          File "/opt/datadog-agent/agent/config.py", line 949, in _load_file_config
            check_config = check_yaml(config_path)
          File "/opt/datadog-agent/agent/util.py", line 119, in check_yaml
            raise Exception('You need to have at least one instance defined in the YAML file for this check')
        Exception: You need to have at least one instance defined in the YAML file for this check

**This is what is in my sqlserver.yaml file**

```
...

instances:
    -host: 127.0.0.1, 1433
    username: datadog
    password: ****
    tags:
      - optional_tag

...
```
I was able to use sqlcmd to connect to the server with the datadog user.
`sqlcmd -Slocalhost -Udatadog -P****` 

any ideas?

**Comment by vin-yu** [comment]
closing issue was a problem with my yaml... here is what it should have looked like.
```
instances:
    - host: 127.0.0.1, 1433
      connector: odbc
      username: datadog
      password: *****
      tags:
      - optional_tag

```
