### ISSUE TITLE
[kubernetes] Kubernetes integration submits high volume of queries for events

### ISSUE THREAD

**Issue by cberner** [DataDog/dd-agent#3381]
**Output of the [info page](https://help.datadoghq.com/hc/en-us/articles/203764635-Agent-Status-and-Information) **

```
2017-06-09 23:44:35,115 | WARNING | dd.collector | utils.service_discovery.config(config.py:31) | No configuration backend provided for service discovery. Only auto config templates will be used.
====================
Collector (v 5.14.0)
====================

  Status date: 2017-06-09 23:44:23 (12s ago)
  Pid: 24
  Platform: Linux-4.4.0-72-generic-x86_64-with-debian-8.8
  Python Version: 2.7.13, 64bit
  Logs: <stderr>, /var/log/datadog/collector.log

  Clocks
  ======

    NTP offset: -0.111 s
    System UTC time: 2017-06-09 23:44:35.231581

  Paths
  =====

    conf.d: /etc/dd-agent/conf.d
    checks.d: /opt/datadog-agent/agent/checks.d

  Hostnames
  =========

    socket-hostname: dd-agent-2ddz7
    hostname: kubernetes-worker-10-85-16-8.dev.openai.org
    socket-fqdn: dd-agent-2ddz7

  Checks
  ======

    ntp (5.14.0)
    ------------
      - Collected 0 metrics, 0 events & 0 service checks

    disk (5.14.0)
    -------------
      - instance #0 [OK]
      - Collected 32 metrics, 0 events & 0 service checks

    docker_daemon (5.14.0)
    ----------------------
      - instance #0 [OK]
      - Collected 157 metrics, 0 events & 1 service check

    kubernetes (5.14.0)
    -------------------
      - initialize check class [ERROR]: ConnectionError(MaxRetryError('None: Max retries exceeded with url: /healthz?verbose=True (Caused by None)',),)

  Emitters
  ========

    - http_emitter [OK]

====================
Dogstatsd (v 5.14.0)
====================

  Status date: 2017-06-09 23:44:30 (4s ago)
  Pid: 18
  Platform: Linux-4.4.0-72-generic-x86_64-with-debian-8.8
  Python Version: 2.7.13, 64bit
  Logs: <stderr>, /var/log/datadog/dogstatsd.log

  Flush count: 315
  Packet Count: 5360
  Packets per second: 1.7
  Metric count: 9
  Event count: 0
  Service check count: 0

====================
Forwarder (v 5.14.0)
====================

  Status date: 2017-06-09 23:44:32 (3s ago)
  Pid: 17
  Platform: Linux-4.4.0-72-generic-x86_64-with-debian-8.8
  Python Version: 2.7.13, 64bit
  Logs: <stderr>, /var/log/datadog/forwarder.log

  Queue Size: 0 bytes
  Queue Length: 0
  Flush Count: 1104
  Transactions received: 645
  Transactions flushed: 645
  Transactions rejected: 0
  API Key Status: API Key is valid


======================
Trace Agent (v 5.14.0)
======================

  Pid: 16
  Uptime: 3158 seconds
  Mem alloc: 964792 bytes

  Hostname: dd-agent-2ddz7
  Receiver: 0.0.0.0:8126
  API Endpoint: https://trace.agent.datadoghq.com

  Bytes received (1 min): 0
  Traces received (1 min): 0
  Spans received (1 min): 0

  Bytes sent (1 min): 0
  Traces sent (1 min): 0
  Stats sent (1 min): 0
```

**Additional environment details (Operating System, Cloud provider, etc):**
Ubuntu 14.04, Kubernetes cluster, Azure

**Steps to reproduce the issue:**
1. Install dd-agent
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: dd-agent
  namespace: daemons
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  template:
    metadata:
      labels:
        app: dd-agent
      name: dd-agent
    spec:
      serviceAccountName: datadog
      containers:
      - image: datadog/docker-dd-agent:latest
        imagePullPolicy: Always
        name: dd-agent
        ports:
          - containerPort: 8125
            name: dogstatsdport
            protocol: UDP
        env:
          - name: API_KEY
            value: xxxxxx
          - name: KUBERNETES
            value: "yes"
          - name: SD_BACKEND
            value: docker
          - name: TAGS
            value: env:${env},cluster:${cluster_name}
        volumeMounts:
          - name: dockersocket
            mountPath: /var/run/docker.sock
          - name: procdir
            mountPath: /host/proc
            readOnly: true
          - name: cgroups
            mountPath: /host/sys/fs/cgroup
            readOnly: true
      volumes:
        - hostPath:
            path: /var/run/docker.sock
          name: dockersocket
        - hostPath:
            path: /proc
          name: procdir
        - hostPath:
            path: /sys/fs/cgroup
          name: cgroups
      dnsPolicy: Default  # Don't use cluster DNS.
```
2. Check audit logs on apiserver, and observe queries from every node in the cluster, like:
`2017-06-09T23:21:37.230676064Z AUDIT: id="db2c5ebe-eb71-48ab-a1a2-8b3b537c916b" ip="10.126.18.37" method="GET" user="system:serviceaccount:daemons:datadog" groups="\"system:serviceaccounts\",\"system:serviceaccounts:daemons\",\"system:authenticated\"" as="<self>" asgroups="<lookup>" namespace="<none>" uri="/api/v1/events"`

**Describe the results you received:**
Too many, expensive, queries to API servers

**Describe the results you expected:**
Datadog should not account for 20%+ of our apiserver traffic
