### ISSUE TITLE
[Kubernetes] Kubernetes cni deployment do not expose statd 

### ISSUE THREAD

**Issue by pegerto** [DataDog/dd-agent#3434]
Hello,

Give a deployment in kubernetes running a cni network, the pod nodeport is not expose, as result the statd port isn't available from the host ip: https://github.com/kubernetes/kubernetes/issues/31307

For example:
```
    image: datadog/docker-dd-agent:latest
    imagePullPolicy: Always
    name: dd-agent
    ports:
    - containerPort: 8125
      hostPort: 8125
      name: dogstatsdport
      protocol: UDP
```
One solution is to use hostnetwork for the pod, do you see any inconvenience for the agent running in host network ?
