### ISSUE TITLE
jmx.yaml.example needs fixes and better documentation

### ISSUE THREAD

**Issue by emersonf** [DataDog/dd-agent#421]
1. The missing space between "-" and "include" on line 10 breaks parsing.
2. What does the YAML key "bean" refer to? MBeans are referenced by ObjectName, and putting an ObjectName here doesn't work. I assumed "bean" was a sample ObjectName key.

There is no documentation I can find which explains how to monitor a specific attribute in a specific MBean, I had to figure it out through trial and error, which is anything but intuitive if you don't know Python and haven't used YAML before. Please add something like the following to the example file.

```
   e.g. for object name domain1:key1=value1,key2=value2,key3=value3 
          with attributes attribute1 and attribute2, use

    conf:
        - include:
           domain: domain1
           key1: value1
           key2: value2
           key3: value3
           attribute:
               attribute1:
                    metric_type: counter
                    alias: jmx.attribute1_metric_name_in_dd   # the name of the metric in dd
               attribute2:
                    metric_type: gauge
                    alias: jmx.attribute2_metric_name_in_dd
```
