### ISSUE TITLE
mongodb.stats.objects seems to misreport

### ISSUE THREAD

**Issue by miketheman** [DataDog/dd-agent#463]
Given:

``` yaml
init_config:

instances:
  - server: mongodb://datadog:<somepwd>@localhost:27017
    tags:
      - mytags
```

And:

``` js
$ mongo
MongoDB shell version: 2.4.2
connecting to: test
fullstack:PRIMARY> db.runCommand('dbstats')
{
    "db" : "test",
    "collections" : 3,
    "objects" : 93885,
    "avgObjSize" : 56.899568621185495,
    "dataSize" : 5342016,
    "storageSize" : 11264000,
    "numExtents" : 9,
    "indexes" : 3,
    "indexSize" : 10833200,
    "fileSize" : 201326592,
    "nsSizeMB" : 16,
    "dataFileVersion" : {
        "major" : 4,
        "minor" : 5
    },
    "ok" : 1
}
```

Something doesn't look right when DD shows me a solid unchanging value of 7.
