### ISSUE TITLE
redis check failing on tags in config

### ISSUE THREAD

**Issue by clofresh** [DataDog/dd-agent#515]
```
    redisdb
    -------
      - initialize check class [OK]
      - instance #0 [ERROR]: TypeError("__init__() got an unexpected keyword argument 'tags'",)
      - instance #1 [ERROR]: TypeError("__init__() got an unexpected keyword argument 'tags'",)
      - Collected 0 metrics & 0 events
```

Must be a regression in 3.7.1 since data just stopped yesterday.

This is the yaml file:

```
init_config:

instances:
    -   host: localhost
        port: 6379
        tags: [livecache, partitions:8-15]
    -   host: localhost
        port: 6380
        tags: [queue]
```
