### ISSUE TITLE
confd yaml parsing

### ISSUE THREAD

**Issue by tbarbugli** [DataDog/dd-agent#645]
Hi,
I am struggling with a config problem.

This is the config i have in a yaml file

```
-  rabbitmq_api_url: http://localhost:55672/api/
   rabbitmq_user: *****
   rabbitmq_pass: *****
   queues:
    - a.b.c
```

looks like using dots breaks the parsing as the queues key is always an empty list

If I set queues to something like
- a
- b
- c

then I get the ['a', 'b', 'c'] set in the configs

I also parsed my configs using yaml and that returned the expected dict back

Do you use the dot char in some special way ?
