### ISSUE TITLE
jmx / tomcat default template should contain database connection monitoring

### ISSUE THREAD

**Issue by ssbarnea** [DataDog/dd-agent#840]
Below are two most used ways to monitor database connections for jmx applications. 
Maybe it would make sense to give them similar aliases so we could properly aggregate them.

Feel free to add your ideas.

Note: the bean name is commented because of a bug that would filter it out if you specify it.

```
    - include:
                type: C3P0Registry
#                bean: "com.mchange.v2.c3p0
                attribute:
                  AllPooledDataSourcesCount:
                    alias: tomcat.c3p0.allpooled
                    metric_type: gauge
                  NumPooledDataSources:
                    alias: tomcat.c3p0.pooled
                    metric_type: gauge
                  NumPoolsAllDataSources:
                    alias: tomcat.c3p0.pools
                    metric_type: gauge
    - include:
        type: DataSource
        attribute:
          numIdle:
            alias: tomcat.datasource.idle
            metric_type: gauge
          numActive:
            alias: tomcat.datasource.active
            metric_type: gauge
          maxIdle:
            alias: tomcat.datasource.maxidle
            metric_type: gauge
          maxActive:
            alias: tomcat.datasource.maxactive
            metric_type: gauge
```
